config/routes.rb
Rails.application.routes.draw do
	root "index#index"
	resources :terms

	match "/404" => "index#error404", via: [ :get, :post, :patch, :delete ]
	match "/panel" => "index#panel", via: [ :get ]
	match "/panel" => "index#manage", via: [ :post ]
end

app/models/associated_mongo_term.rb
class AssociatedMongoTerm
  include Mongoid::Document

  field :term, type: String
  index "term" => 1

	has_many :mongo_meanings, :dependent => :destroy
	belongs_to :mongo_declension
	belongs_to :mongo_gender
	belongs_to :mongo_term_number
	belongs_to :mongo_ending

	# accepts_nested_attributes_for :meanings
	
	# TERM_FORMAT = /\A([А-Яа-яЁё][А-Яа-яЁё ]*)+\z/
	# validates :term, :presence => true, :format => TERM_FORMAT, :uniqueness => true

end

app/models/declension.rb
class Declension < ActiveRecord::Base
	has_many :terms

	validates :content, {
		:presence => true, 
		:uniqueness => true, 
		:inclusion => { :in => %w(first second third empty) },
	}
end

app/models/ending.rb
class Ending < ActiveRecord::Base
	has_many :terms

	validates :content, :presence => true, :uniqueness => true
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :terms

	validates :content, { 
		:presence => true,
		:inclusion => { :in => %w{masculine feminine neuter empty} },
		:uniqueness => true,
	}
end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
	belongs_to :term

	validates :content, :presence => true
end

app/models/mongo_declension.rb
class MongoDeclension
  include Mongoid::Document

  field :declension, type: String
  index "declension" => 1

	has_many :associated_mongo_term, :dependent => :destroy
	
	ENDING_FORMAT = /\A[а-яё]+\z/

	DECLENSION_INCLUSIONS = %w(first second third empty)

	validates :declension, {
		:presence => true, 
		:inclusion => { :in => DECLENSION_INCLUSIONS },
	}

end

app/models/mongo_ending.rb
class MongoEnding
  include Mongoid::Document

  field :ending, type: String
  index "ending" => 1

	has_many :associated_mongo_term

	# ENDING_FORMAT = /\A[а-яё]+\z/

	# validates :ending, :presence => true, :format => ENDING_FORMAT
end

app/models/mongo_gender.rb
class MongoGender
  include Mongoid::Document

  field :gender, type: String
  index "gender" => 1

	has_many :associated_mongo_term, :dependent => :destroy
	
	GENDER_INCLUSIONS = %w{masculine feminine neuter empty}

	validates :gender, { 
		:presence => true,
		:inclusion => { :in => GENDER_INCLUSIONS },
	}

end

app/models/mongo_meaning.rb
class MongoMeaning
  include Mongoid::Document

  field :meaning, type: String
  index "meaning" => 1

	belongs_to :associated_mongo_term
	validates :meaning, :presence => true

end

app/models/mongo_term.rb
class MongoTerm
  include Mongoid::Document

	TERM_FORMAT = /\A([А-Яа-яЁё][А-Яа-яЁё ]*)+\z/
	# ENDING_FORMAT = /\A[а-яё]+\z/

	DECLENSION_INCLUSIONS = %w(first second third empty)
	GENDER_INCLUSIONS = %w{masculine feminine neuter empty}
	TERM_NUMBER_INCLUSIONS = %w{singular plural empty}

  field :term, type: String
  field :meanings, type: Array
  field :ending, type: String
  field :declension, type: String
  field :gender, type: String
  field :term_number, type: String

  index "term" => 1
  index "ending" => 1
  index "declension" => 1
  index "gender" => 1
  index "term_number" => 1

	# validates :term, :presence => true, :format => TERM_FORMAT, :uniqueness => true
	# validates :meanings, :presence => true
	# validates :ending, :presence => true, :format => ENDING_FORMAT
	validates :declension, {
		:presence => true, 
		:inclusion => { :in => DECLENSION_INCLUSIONS },
	}
	validates :gender, { 
		:presence => true,
		:inclusion => { :in => GENDER_INCLUSIONS },
	}
	validates :term_number, {
		:presence => true , 
		:inclusion => { :in => TERM_NUMBER_INCLUSIONS }
	}

end

app/models/mongo_term_number.rb
class MongoTermNumber
  include Mongoid::Document

  field :term_number, type: String
  index "term_number" => 1

	has_many :associated_mongo_term
	TERM_NUMBER_INCLUSIONS = %w{singular plural empty}

	validates :term_number, {
		:presence => true , 
		:inclusion => { :in => TERM_NUMBER_INCLUSIONS }
	}
end

app/models/similar_term.rb
class SimilarTerm < ActiveRecord::Base
	belongs_to :parent_term, {
		:foreign_key => "parent_term_id",
		:class_name => "Term",
	}
	belongs_to :child_term, {
		:foreign_key => "child_term_id",
		:class_name => "Term",
	}
end

app/models/term.rb
class Term < ActiveRecord::Base
	CONTENT_FORMAT = /\A([А-Яа-яЁё][А-Яа-яЁё ]*)+\z/

	has_many :meanings, :dependent => :destroy
	belongs_to :declension
	belongs_to :gender
	belongs_to :term_number
	belongs_to :ending

	accepts_nested_attributes_for :meanings

	has_and_belongs_to_many( :similar_terms, {
			:class_name => "Term",
			:join_table => "similar_terms",
			:foreign_key => "parent_term_id",	
			:association_foreign_key => "child_term_id",
		}
	)

	# validates :content, :presence => true, :format => CONTENT_FORMAT, :uniqueness => true
end

app/models/term_number.rb
class TermNumber < ActiveRecord::Base
	has_many :terms

	validates :content, :presence => true , :uniqueness => true, :inclusion => { :in => %w{singular plural empty} }

end

app/models/word_case.rb
class WordCase < ActiveRecord::Base
	belongs_to :declension
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  	# change to eagerload
    # @data = Term.eager_load(:meanings).eager_load(:term_number).eager_load(:gender).eager_load(:declension)
  end

  def error404
  	render :status => :not_found
  end

  def panel
  end 

  def manage
  	if !params[:query].nil? && !params[:query].empty?
      @query = params[:query]
	  	@connection = ActiveRecord::Base.establish_connection(
				:adapter  => Rails.configuration.database_configuration[Rails.env]["adapter"],
				:host     => Rails.configuration.database_configuration[Rails.env]["host"],
				:database => Rails.configuration.database_configuration[Rails.env]["database"],
				:username => Rails.configuration.database_configuration[Rails.env]["username"],
				:password => Rails.configuration.database_configuration[Rails.env]["password"],
			)
      begin
  			@results = @connection.connection.execute(params[:query])
      rescue ActiveRecord::StatementInvalid => error
        @sql_error = error
      end
		end
  	render :action => "panel"
  end

end

app/controllers/terms_controller.rb
class TermsController < ApplicationController

	def index
		@terms = Term.eager_load(:meanings, :declension, :gender, :term_number).page(params[:page]).order(:content)
	end

	def show
		@term = Term.eager_load(:meanings, :declension, :gender, :term_number).find(params[:id])
	end 

	def edit
		flash = nil
		# toDO: Рефактор
		@term = Term.eager_load(:meanings, :declension, :gender, :term_number).find(params[:id])
	end

	def update
		@term = Term.find(params[:id])
		if @term.update(term_params)
			flash[:status] = "success" 
			redirect_to term_path(@term)
		else
			flash[:status] = "failed"
			render :action => "edit"
		end
	end

	def destroy
		term = Term.find_by(:id => params[:id])
		flash[:status] = "failed"
		if term
				term.destroy
				flash[:status] = "success"
				flash[:message] = I18n.t("messages.term.delete.#{flash[:status]}", :word => term.content)
		else
			flash[:message] = I18n.t("messages.term.delete.#{flash[:status]}")
		end
		redirect_to terms_path
	end

	def new	
		@term = Term.new	
	end

	def create
		@term = Term.new(term_params)
		# toDo: допилить с учётом тестов
		if @term.save
			redirect_to terms_path
		else
			render :action => 'new'
		end
	end

	private 

		def term_params
			params.require(:term).permit(
				:content, 
				:gender_id, 
				:declension_id, 
				:term_number_id, 
				:meanings_attributes => [
					:id, 
					:content
				]
			)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def set_up_query(query)
		query ||= ""
	end
end

app/helpers/term_helper.rb
module TermHelper
	
	def generate_data_for_select_tag (object)
		output = []
		object.all.each do | item |
				output << [
					I18n.t("models.#{object}.attributes.content.values.#{item.content}".underscore),
					item.id
				]
		end
		output
	end

	def nested_term_for_meanings(term)
		term.meanings = [ Meaning.new ] unless term.meanings.any?
		term
	end
	
end

app/views/index/error404.html.slim
.404
	| Страница, которую вы ищете, не существует

app/views/index/panel.html.slim
.content
	= form_tag '/panel'
		= text_area_tag 'query', set_up_query(@query), :class => "query_field", :placeholder => t("titles.placeholders.query-area")
		= button_tag t('titles.buttons.execute'), :class => "button"
	- unless @sql_error.nil?
		.flash.failed
			= @sql_error

	- unless @results.nil?
		table.results
			thead
				tr
					td colspan=@results.first.keys.count
						= t "titles.table.sql-results"
				tr
					- @results.first.keys.each do | key |
						td
							b
								= key
			tbody
				- @results.each do | row |
					tr class=cycle('list_line_odd', 'list_line_event')
						- row.each do | key , value |
							td 
								= value

app/views/layouts/application.html.slim
html
	head
		title
			= t("titles.page_titles.index.index") + " - " + t("titles.page_titles.#{controller_name}.#{action_name}")
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	body
		.wrapper
			.site-menu
				ul.site-menu
					li
						= link_to t("titles.menu_titles.terms_list"), terms_path
					li
						= link_to t("titles.menu_titles.create_term"), new_term_path
					li
						= link_to t("titles.page_titles.index.panel"), "/panel"
			.page-title
				= t("titles.page_titles.#{controller_name}.#{action_name}")
			=yield

app/views/terms/edit.html.slim
.content
	= form_for @term, :html => { :class => "edit_form" } do | f |
		
		- if !@term.nil? && @term.errors.any?
			.errors_container
				- @term.errors.each do | field , message |
					.error-message
						= message
				
		.input_container
			= f.label :content, t("models.term.one")
			= f.text_field :content

		.input_container
			= f.label :gender_id, t("models.gender.one")
			= f.select :gender_id, generate_data_for_select_tag(Gender)

		.input_container
			= f.label :declension_id, t("models.declension.one")
			= f.select :declension_id, generate_data_for_select_tag(Declension)

		.input_container
			= f.label :term_number_id, t("models.term_number.one")
			= f.select :term_number_id, generate_data_for_select_tag(TermNumber)

		.input_container
			= label_tag "meanings", t('models.meaning.many')
			= f.fields_for :meanings, @term.meanings do | meaning |
				= meaning.text_area :content
		.buttons_container
			=f.submit t('titles.buttons.submit'), :class => "button"

app/views/terms/index.html.slim
.flash *{ :class => [flash[:status]] }
	= flash[:message]
- unless @terms.nil? || @terms.empty?
	.content
		.main-items-list-container
				- @terms.each do | term | 
					.main-items-list-item
						.term
							= link_to term.content, term_path(term)
							= link_to " (" + t('titles.buttons.delete') + ")", term, :method => :delete, :class => 'delete-link', :data => {:confirm => t('messages.confirmation.delete', :entity => term.content)}
							.gender
								b
									= t("models.gender.one") + ": "
								= t("models.gender.attributes.content.values.#{term.gender.content}")
							.declension	
								b
									= t("models.declension.one") + ": "
								= t("models.declension.attributes.content.values.#{term.declension.content}")
							.term-number
								b
									= t("models.term_number.one") + ": "
								= t("models.term_number.attributes.content.values.#{term.term_number.content}")

						.meaning-container
							- term.meanings.each do | meaning |
								.meaning-item
									= meaning.content
		.paginate-container
			= will_paginate @terms
		/ .paginate-container
		/ 	ul
		/ 		li 
		/ 			| 1
		/ 		li
		/ 			| 2
		/ 		li
		/ 			| 3
		/ 		li
		/ 			| 4
- else
	= t("models.term.empty")

app/views/terms/new.html.slim
.content
	= form_for nested_term_for_meanings(@term), :url => terms_path, :html => { :class => "edit_form" } do | f |
		- if !@term.nil? && @term.errors.any?
			.errors_container
				- @term.errors.each do | field , message |
					.error-message
						= message
					
		.input_container
			= f.label :content, t("models.term.one") 
			= f.text_field :content

		.input_container
			= f.label :gender_id, t("models.gender.one")
			= f.select :gender_id, generate_data_for_select_tag(Gender)

		.input_container
			= f.label :declension_id, t("models.declension.one")
			= f.select :declension_id, generate_data_for_select_tag(Declension)

		.input_container
			= f.label :term_number_id, t("models.term_number.one")
			= f.select :term_number_id, generate_data_for_select_tag(TermNumber)

		.input_container#meanings_container
			= label_tag "meanings", t("models.meaning.many")
			= f.fields_for :meanings, @term.meanings do | meaning |
				= meaning.text_area :content

		.buttons_container
			= f.submit t("titles.buttons.submit"), :class => "button"
			= link_to t("titles.buttons.add_new_meaning"), "", :class => "button", :id => "add_new_meaning"
			= link_to t("titles.buttons.delete_meaning"), "", :class => "button", :id => "delete_meaning"

app/views/terms/show.html.slim
.content
	- unless @term.nil?
		.info_container
			.attribute_container
				.attribute-name
					=' t("models.term.one") + ":"
				.attribute-value
					= @term.content

			.attribute_container
				.attribute-name
					=' t("models.gender.one") + ":"
				.attribute-value
					= t("models.gender.attributes.content.values.#{@term.gender.content}")

			.attribute_container
				.attribute-name
					=' t("models.declension.one") + ":"
				.attribute-value
					= t("models.declension.attributes.content.values.#{@term.declension.content}")

			.attribute_container
				.attribute-name
					=' t("models.term_number.one") + ":"
				.attribute-value
					= t("models.term_number.attributes.content.values.#{@term.term_number.content}")

			.attribute_container
				.attribute-name
					=' t("models.meaning.many") + ":"
				- if @term.meanings.any?
					- @term.meanings.each do | meaning |
						.attribute-value
							= meaning.content
				- else
					= t("models.meaning.empty")
			.buttons_container
				= link_to t("titles.buttons.edit"), edit_term_path(@term), :class => "button"
				= link_to t("titles.buttons.delete"), term_path(@term), method: :delete, class: "button", :data => { :confirm => t('messages.confirmation.delete', :entity => @term.content) }